### ISSUE TITLE
关于使用教程

### ISSUE THREAD

**Issue by XmJwit** [CodingPokemon/mirai-Kyaru#3]
## 请问大佬有具体的搭建使用教程吗？
我用的是IDEA
![PY](https://user-images.githubusercontent.com/36185379/89302981-1f81d280-d69e-11ea-8add-bd9fc200b9b0.gif)

**Comment by TyranitarX** [comment]
鉴于现在的形势 你如果需要mirai-console的话自己找一个吧 如果需要源码会用idea应该不需要我教吧（
